config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/categories', to: 'pages#categories'
  get '/profile/:id', as: 'profile', to: 'users#show'
  get '/:id/booking', as: 'users_bookings', to: 'users#bookings'
  get '/providers/all', as: 'all_providers', to: 'providers#all' 
  resources :providers do
    get 'provider/:id/bookings/:id/confirmation',as: 'booking_confirmation', to: 'bookings#confirmation'
    resources :bookings do
      resources :payments, only: :new
    end
    resources :reviews, only: :create
  end
  resources :chatrooms, only: [:new, :create, :show, :index] do 
    resources :messages, only: :create
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/provider.rb
class Provider < ApplicationRecord

  include PgSearch::Model

  pg_search_scope :global_search,
    against: [ :service_type, :name ],
  #   associated_against: {
  #     users: [ :username, :service_type ]
  # },
    using: {
      tsearch: { prefix: true }
  }

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  serialize :languages
  belongs_to :user
  has_many_attached :photos
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :chatrooms, dependent: :destroy
  validates :name, :service_type, :rate, :location, :description, :languages, presence: true
  validates :name, uniqueness: true

  def rating
    return 0 if self.reviews.empty?

    total = self.reviews.sum(:rating)
    total / self.reviews.count
  end
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
	skip_before_action :authenticate_user!, only: [:index, :all]
	before_action :get_location, only: [:index, :all]
	def index
		@providers = policy_scope(Provider).where(service_type: params[:format]).near([session[:latitude], session[:longitude]], 600)
		@markers = @providers.geocoded.map do |provider|
			{
			  lat: provider.latitude,
			  lng: provider.longitude,
			  infoWindow: render_to_string(partial: "info_window", locals: { provider: provider })
			}
		end
	end

	def all
		@providers = policy_scope(Provider).all.near([session[:latitude], session[:longitude]], 600)
		@markers = @providers.geocoded.map do |provider|
			{
			  lat: provider.latitude,
			  lng: provider.longitude,
			  infoWindow: render_to_string(partial: "info_window", locals: { provider: provider })
			}
		end
	end

	def show
		@provider = Provider.find(params[:id])
		@booking = Booking.new
		@review = Review.new
		authorize @provider
	end

	def new
		@provider = Provider.new
		authorize @provider
	end

	def create
		@provider = Provider.new(providers_params)
		@provider.user = current_user
		@provider.user.provider = true
		@provider.user.save!
		if @provider.save!
			redirect_to provider_path(@provider)
		else
			render :new
		end
		authorize @provider
	end

	def edit
	
	end
	def update
	end

	def destroy
	
	end

	private

	def get_location
		if params[:latitude].present? && params[:longitude].present?
			session[:latitude] = params[:latitude]
			session[:longitude] = params[:longitude]
		end
	
		if params[:location].present?
			results = Geocoder.search(params[:location])
			results.first.coordinates
		
			session[:latitude] = results.first.coordinates.first
			session[:longitude] = results.first.coordinates.last
		end

		if params[:query].present?
			@providers = policy_scope(Provider).global_search(params[:query])
		elsif params[:service_type].present?
			@providers = policy_scope(Provider).where(service_type: params[:service_type])
		else
			@providers = policy_scope(Provider)
		end
	end

	def providers_params
		params.require(:provider).permit(:name, :description, :location, :rate, :service_type, :languages, photos: [])
	end
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/views/providers/_info_window.html.erb
<%= link_to provider_path(provider), class: 'text-decoration-none text-secondary' do %>
  <%= cl_image_tag( provider.photos.first.key, :width => '100%', :height => 100, gravity: 'face') %>
  <div class="provider-card-infos py-1 px-2">
      <h2 class="mt-2 mb-0"><%= provider.name  %></h2>
      <%# <!--<p><%= bar.distance_to([session[:latitude].to_f, session[:longitude].to_f]).ceil(2) km away</p>%> 
      <p class="mb-0"><%= provider.service_type %></p>
      <div class="d-flex align-items-center justify-content-between">
        
        <% if provider.rating == 0 %>
            <p class="mb-0">Not rated yet</p>
        <% else %>
            <p class="mb-0"><% provider.rating.times do %><i class="fas fa-star text-secondary"></i><% end %> <%= pluralize provider.reviews.size, "review" %></p>
        <% end %>
        
        <p class="mb-0"><%= number_to_currency(provider.rate, unit: '€') %></p>
      </div>
    </div>
  </div>
<% end %>

app/views/providers/all.html.erb
<div class="container provider-index-container" data-controller="toggle-map">
    <div class="toggle-button-container">
        <button class="toggle-view btn btn-secondary" data-toggle-map-target="toggleButton" data-action="click->toggle-map#toggle" id="toggleButton">
            Toggle view <i class="fas fa-map-marked-alt ml-2"></i>
        </button>
    </div>
    <div class="row">
        <div class="col-12 col-lg-6 transition"  data-toggle-map-target="listView">
            <% @providers.each do |provider| %>
                <div class="card my-3 m-auto" style="max-width: 768px;">
                    <div class="row g-0">
                        <div class="col-md-4">
                            <%= cl_image_tag provider.photos[0].key, class:'provider-image', crop: :fill, gravity: :face %>
                        </div>
                        <div class="col-md-8">
                            <div class="card-body shadow-lg index-provider-card-body">
                                <h5 class="card-title"><%= provider.name.upcase %></h5>
                                <p class="card-text fw-bolder"><%= provider.service_type %></p>
                                <div class="d-flex justify-content-start flex-wrap">
                                <% languages = provider.languages.split(', ') %>
                                    <% languages.each do |language| %>
                                        <h5><span class="badge bg-secondary me-3 fw-normal"><%= language %></span></h5>
                                    <% end %>
                                </div>
                                <p class="card-text text-truncate"><%= provider.description %></p>
                                <p class="card-text"><small class="text-muted">Rate: €<%= provider.rate %></small></p>
                                <%= link_to 'More info', provider_path(provider.id), class: 'btn btn-secondary' %>
                            </div>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
        <div class="col-12 col-lg-6 my-3" data-toggle-map-target="mapView">
            <div id="map" style="width: 100%; height: 600px;" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
            </div>
            
        </div>
    </div>
</div>

app/views/providers/index.html.erb
<div class="container provider-index-container" data-controller="toggle-map">
    <div class="toggle-button-container">
        <button class="toggle-view btn btn-secondary" data-toggle-map-target="toggleButton" data-action="click->toggle-map#toggle" id="toggleButton">
            Toggle view <i class="fas fa-map-marked-alt ml-2"></i>
        </button>
    </div>
    <div class="row">
        <div class="col-12 col-lg-6 transition"  data-toggle-map-target="listView">
            <% @providers.each do |provider| %>
                <div class="card my-3 m-auto" style="max-width: 768px;">
                    <div class="row g-0">
                        <div class="col-md-4">
                            <%= cl_image_tag provider.photos[0].key, class:'provider-image', crop: :fill, gravity: :face %>
                        </div>
                        <div class="col-md-8">
                            <div class="card-body shadow-lg index-provider-card-body">
                                <h5 class="card-title"><%= provider.name.upcase %></h5>
                                <p class="card-text fw-bolder"><%= provider.service_type %></p>
                                <div class="d-flex justify-content-start flex-wrap">
                                <% languages = provider.languages.split(', ') %>
                                    <% languages.each do |language| %>
                                        <h5><span class="badge bg-secondary me-3 fw-normal"><%= language %></span></h5>
                                    <% end %>
                                </div>
                                <p class="card-text text-truncate"><%= provider.description %></p>
                                <p class="card-text"><small class="text-muted">Rate: €<%= provider.rate %></small></p>
                                <%= link_to 'More info', provider_path(provider.id), class: 'btn btn-secondary' %>
                            </div>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
        <div class="col-12 col-lg-6 my-3" data-toggle-map-target="mapView">
            <div id="map" style="width: 100%; height: 600px;" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
            </div>
            
        </div>
    </div>
</div>

app/views/providers/new.html.erb
<div class="container-fluid new-provider-body">
	<div class="row">
		<div class="col-12 col-md-10 col-lg-6 m-auto">
			<div class="new-provider-container">
				<h1>Become a provider</h1>
				<%= form_for(@provider) do |f| %>
					<div class="field">
						<%= f.file_field :photos, as: :file,  multiple: true  %>
					</div>
					<div class="field">
						<%= f.label :name %>
						<%= f.text_field :name, class: 'input-background' %>
					</div>
					<div class="field">
						<%= f.label :service_type %>
						<%= f.text_field :service_type, class: 'input-background' %>
					</div>
						<div class="field">
						<%= f.label :rate %>
						<%= f.number_field :rate,  step: :any, class: 'input-background' %>
					</div>	
					<div class="field">
						<%= f.label :address %>
						<%= f.text_field :location, class: 'input-background' %>
					</div>
					<div class="field">
						<%= f.label :languages %>
						<%= f.text_field :languages, class: 'input-background' %>
					</div>
					<div class="field">
						<%= f.label :description %>
						<%= f.text_field :description, class: 'input-background' %>
					</div>			
					<%= f.submit "Register", class: 'btn btn-secondary mt-3' %>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/providers/show.html.erb
<div class="container-fluid provider-show-container">
    <div class="row">
        <div class="col-12 col-md-10 col-lg-6  m-auto"> 
            <div class="provider-show-info-container">
                <%= cl_image_tag @provider.photos[0].key, height: 250, width: 250, crop: :fill %>
                <div class="profile-info">
                    <div>
                        <h1><%= @provider.name %></h1> 
                        <% if @provider.rating == 0 %>
                            <p>Not rated yet</p>
                        <% else %>
                        <p><% @provider.rating.times do %><i class="fas fa-star text-secondary"></i><% end %> <%= pluralize @provider.reviews.size, "review" %></p>
                        <% end %>
                    </div>
                    
                    <div>
                        <h6><i class="fas fa-graduation-cap"></i> <%= @provider.service_type %></h6>
                    </div>
                    <div>
                        <h6><i class="far fa-envelope"></i> <%= @provider.user.email %></h6>
                    </div>
                    <div>
                        <h6><i class="fas fa-map-pin"></i> <%= @provider.location %></h6>
                    </div>
                    <div>
                        <h6>
                        <i class="fas fa-language"></i>
                        <% languages = @provider.languages.split(', ') %>
                        <% languages.each do |language| %>
                            <%= language %>
                        <% end %>
                        </h6>
                    </div>
                    <div>
                        <h6><i class="fas fa-money-bill"></i> €<%= @provider.rate %></h6>
                    </div>
                </div>
            </div>
            <div class="provider-show-info-container">
                <div>
                    <h4>About me</h4>
                    <p><%= @provider.description %></p>
                    <p>Have questions?</p>
                </div>
                <div class="actions w-100 m-auto text-center pt-2">
                    <%= link_to 'Send me a message',  new_chatroom_path(@provider), class: 'btn btn-secondary'  %>
                </div>
            </div>
            <div class="provider-show-info-container">
                <h3>Ready to book <%= @provider.name %> Services</h3>
                <div class="actions w-100 m-auto text-center pt-2">
                    <%= link_to 'Book now',  new_provider_booking_path(@provider), class: 'btn btn-secondary'  %>
                </div>
            </div>
            <div class="provider-show-info-container">
                <h3><%= @provider.name %> reviews</h3>
                <% if @provider.reviews.nil? || @provider.reviews.length == 0%>
                    <p>Be the first to review <%= @provider.name %>.</p>
                <% else %>
                    <% @provider.reviews.each do |review| %>
                        <div class="review-container shadow">
                            <% review.rating.times do %>
                                <i class="fas fa-star"></i>
                            <% end %>
                            <p class="mb-0"><%= review.content.capitalize %></p>
                        </div>
                    <% end %>
                <% end %>
                <%= form_for([@provider, @review]) do |f| %>
                    <div class="field">
                        <%= f.label :rating %>
                        <%= f.select(:rating, 1..5) %>
                    </div>
                    <div class="field">
                        <%= f.label :content %>
                        <%= f.text_area :content %>
                    </div>
                    <div class="actions w-100 m-auto text-center pt-2">
                        <%= f.submit 'Add review', class: 'btn btn-secondary' %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>