config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/categories', to: 'pages#categories'
  get '/profile/:id', as: 'profile', to: 'users#show'
  get '/:id/booking', as: 'users_bookings', to: 'users#bookings'
  get '/providers/all', as: 'all_providers', to: 'providers#all' 
  resources :providers do
    get 'provider/:id/bookings/:id/confirmation',as: 'booking_confirmation', to: 'bookings#confirmation'
    resources :bookings do
      resources :payments, only: :new
    end
    resources :reviews, only: :create
  end
  resources :chatrooms, only: [:new, :create, :show, :index] do 
    resources :messages, only: :create
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :provider
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  belongs_to :user
  belongs_to :provider
  has_many :messages, dependent: :destroy
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :provider
  belongs_to :chatroom
end

app/models/provider.rb
class Provider < ApplicationRecord

  include PgSearch::Model

  pg_search_scope :global_search,
    against: [ :service_type, :name ],
  #   associated_against: {
  #     users: [ :username, :service_type ]
  # },
    using: {
      tsearch: { prefix: true }
  }

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  serialize :languages
  belongs_to :user
  has_many_attached :photos
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :chatrooms, dependent: :destroy
  validates :name, :service_type, :rate, :location, :description, :languages, presence: true
  validates :name, uniqueness: true

  def rating
    return 0 if self.reviews.empty?

    total = self.reviews.sum(:rating)
    total / self.reviews.count
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :provider
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :photo
  has_many :bookings
  has_many :reviews
  has_many :chatrooms
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = policy_scope(Booking).where(user_id: current_user.id)
    provider = Provider.find_by(user_id: current_user.id)
    @requests = Booking.count > 0 ? Booking.where(provider_id: provider.id) : []
    
    authorize @bookings
  end

  def new
    @booking = Booking.new
    @provider = Provider.find(params[:provider_id])
  end
  def show
    @booking = current_user.bookings.find(params[:id])
  end

  def create
    @booking = Booking.new(booking_params)
    @provider = Provider.find(params[:provider_id])
    @booking.provider = @provider
    @booking.user = current_user
    @booking.save!
    session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      line_items: [{
        name: @booking.provider.name,
        amount: @booking.provider.rate.to_i * 100,
        currency: 'eur',
        quantity: 1
      }],
      success_url:  provider_booking_confirmation_url(@provider, @booking),
      cancel_url: provider_url(@booking.provider)
    )
    
    @booking.update(checkout_session_id: session.id)
    redirect_to new_provider_booking_payment_path(@provider, @booking)
  end

  def destroy
    @booking = Booking.find(params[:id])
    @user = User.find(@booking.user_id)
    @booking.destroy
    redirect_to profile_path(@user)
  end

  def confirmation
    @booking = Booking.find(params[:id])
    @booking.pending = false
    @booking.save!
    redirect_to provider_bookings_path(@booking.provider)
  end

  private

  def booking_params
    params.require(:booking).permit(:date, :time, :user, :provider_id, :comments)
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
    def new
        create
    end
    def create
        @user = current_user
        @provider = Provider.find(params[:format])
        @chatroom = Chatroom.find_by(user: @user, provider: @provider)
        if @chatroom
            redirect_to chatroom_path(@chatroom)
        else
            @chatroom = Chatroom.create!(user: @user, provider: @provider)
            redirect_to chatroom_path(@chatroom)
        end
    end
    def index
        @provider = Provider.find_by(user_id: current_user.id)
        @provider_chats = policy_scope(Chatroom).where(user_id: current_user.id)
        @user_chats = current_user.provider ?  policy_scope(Chatroom).where(provider_id: @provider.id) : []
        
        authorize @provider_chats
        authorize @user_chats
    end

    def show
        @chatroom = Chatroom.find(params[:id])
        @message = Message.new
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @chatroom = Chatroom.find(params[:chatroom_id])
    @message = Message.new(message_params)
    @message.chatroom = @chatroom
    @message.user = current_user
    @message.provider = @chatroom.provider
    if @message.save!
      ChatroomChannel.broadcast_to(
        @chatroom,
        render_to_string(partial: "message", locals: { message: @message }) 
      )
    else
      raise
    end
  end

  private
  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    skip_before_action :authenticate_user!, only: [:home, :categories]
    def home
    end

    def categories
        @categories = []
        
        Provider.all.each do |provider|
            @categories << provider.service_type
        end
    end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
    def new
        @booking = current_user.bookings.where(pending: true).find(params[:booking_id])
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    def create
        @review = Review.new(review_params)
        @review.user = current_user
        @provider = Provider.find(params[:provider_id])
        @review.provider_id = @provider.id
        if @review.save!
            redirect_to provider_path(@provider)
        else

        end

    end

    private

    def review_params
        params.require(:review).permit(:rating, :content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id])
        
        @provider = Provider.find_by(user_id: @user.id)
        if @provider.nil? 
            @request = []
        else
            @requests = Booking.count > 0 ? Booking.where(provider_id: @provider.id) : []
        end
        authorize @user
    end

    def bookings
        @bookings = Booking.where(user_id: current_user.id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookings/confirmation.html.erb
<div class="container-fuild booking-show-container">
    <div class="row">
		<div class="col-12 col-md-10 col-lg-6 m-auto">
            <div class="booking-show-info-container">
                <h3>Your booking has been confirmed!</h3>
                <%= cl_image_tag @booking.provider.photos[0].key, height: 250, width: 250, crop: :fill %>
                <h2><%= @booking.provider.name %></h2>
                <h5><i class="fas fa-graduation-cap"></i>  <%= @booking.provider.service_type %></h5>
                <h5><i class="far fa-calendar"></i> <%= @booking.date.strftime("%a %b %d, %Y") %></h5>
                <h5><i class="far fa-clock"></i> <%= @booking.time.strftime("%I:%M %p") %></h5>
                <h5><i class="fas fa-money-bill"></i> €<%= @booking.provider.rate %></h5>
                <% if @booking.pending %>
                    <div class="alert alert-danger" role="alert">
                        Pending booking payment
                    </div>
                <% else %>
                    <div class="alert alert-success" role="alert">
                        Booking confimed
                    </div>
                <% end %>
                <h5><%= @booking.user.username %> message:</h5>
                <p><%= @booking.comments %></p>
            </div>
        </div>
    </div>
</div>

app/views/bookings/index.html.erb
<div class="container-fluid booking-index-container">
    <div class="row pt-5">
        <div class="col-12 col-md-10 col-lg-6 m-auto pt-5">
            <% if user_signed_in? %>
            <div class="profile-action">
                <nav>
                    <div class="nav nav-tabs" id="nav-tab" role="tablist">
                    <a class="nav-link active w-50 text-secondary" id="nav-bookings-tab" data-bs-toggle="tab" href="#nav-bookings" role="tab" aria-controls="nav-bookings" aria-selected="true">Your bookings</a>
                    <a class="nav-link w-50 text-secondary" id="nav-request-tab" data-bs-toggle="tab" href="#nav-request" role="tab" aria-controls="nav-request" aria-selected="false">Your requests</a>
                    </div>
                </nav>
                <div class="tab-content" id="nav-tabContent">
                    <div class="tab-pane fade show active" id="nav-bookings" role="tabpanel" aria-labelledby="nav-bookings-tab">
                        <% if !current_user.bookings.empty? %>
                            <% current_user.bookings.each do |booking| %>
                            <div class="card mb-3 m-auto" style="max-width: 540px;">
                                <div class="row g-0">
                                <div class="col-md-4">
                                    <%= cl_image_tag booking.provider.photos[0].key, crop: :fill, gravity: :face, class: 'bookings-provider-image' %>
                                </div>
                                <div class="col-md-8">
                                    <div class="card-body">
                                    <h5 class="card-title"><%= booking.provider.name %></h5>
                                    <h6 class="card-text"><%= booking.provider.service_type %></h6>
                                    <p class="card-text mb-0"><i class="fas fa-money-bill-wave"></i> €<%= booking.provider.rate %></p>
                                    <p class="card-text mb-0"><i class="fas fa-map-pin"></i> <%= booking.provider.location %></p>
                                    <p class="card-text mb-0"><i class="fas fa-clock"></i> <%= booking.date.strftime("%a %b %d, %Y") %> - <%= booking.time.strftime("%H:%M") %></p>
                                    <p class="card-text mb-0"><i class="fas fa-language"></i>
                                        <% languages = booking.provider.languages.split(', ') %>
                                        <% languages.each do |lan| %>
                                        <span><%= lan %></span>
                                        <% end %>
                                    </p>
                                    <p class="card-text">Comments: <%= booking.comments %></p>
                                    </div>
                                </div>
                                </div>
                            </div>
                            <% end %>
                        <% else %>
                            <h6 class="">You have not book services yet.</h6>
                        <% end %>
                        </div>
                        <div class="tab-pane fade" id="nav-request" role="tabpanel" aria-labelledby="nav-request-tab">
                        <% if !@requests.empty? || @requests.nil? %>
                            <% @requests.each do |booking| %>
                            <div class="card mb-3 m-auto" style="max-width: 540px;">
                                <div class="row g-0">
                                <div class="col-md-4">
                                    <% if !booking.user.photo.attachment.nil? %>
                                        <%= cl_image_tag booking.user.photo.key, crop: :fill, gravity: :face, class: 'bookings-provider-image' %>
                                    <% else %>
                                        <img src="https://res.cloudinary.com/dliczkabg/image/upload/v1610983854/profile-silhouette_oychwo.jpg" alt="" class="bookings-provider-image">
                                    <% end %>
                                </div>
                                <div class="col-md-8">
                                    <div class="card-body">
                                    
                                    <h5 class="card-title mb-0"><%= booking.user.username %></h5>
                                    <% if booking.pending %>
                                        <div class="alert alert-warning mb-0" role="alert">
                                        Pending for approval
                                        </div>
                                    <% else %>
                                        <div class="alert alert-success mb-0" role="alert">
                                        Booking confirmed
                                        </div>
                                    <% end %>
                                    <p class="card-text mb-0"><i class="fas fa-clock"></i> <%= booking.date.strftime("%a %b %d, %Y") %> - <%= booking.time.strftime("%H:%M") %></p>
                                    <p class="card-text mb-0">Comments: <%= booking.comments %></p>
                                    <div>
                                        <%= link_to "Accept", provider_booking_confirmation_path(booking.provider, booking.id), method: :get, data: { confirm: "Are you sure?" }, class: "btn btn-secondary btn-sm mr-2" %>
                                        <%= link_to "Reject", provider_booking_path(booking.user, booking.id), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-secondary btn-sm" %>
                                    </div>
                                    </div>
                                </div>
                                </div>
                            </div>
                            <% end %>
                        <% else %>
                            <h6 class="">You don't have booking requests yet.</h6>
                        <% end %>
                        </div>
                    </div>
                    </div>
                <% end %>
        </div>
    </div>
</div>

app/views/bookings/new.html.erb
<div class="container-fluid new-booking-container">
	<div class="row">
		<div class="col-12 col-md-10 col-lg-6 m-auto">
			<div class="new-booking-form-container">
                <h3>Hire <%= @provider.name %></h3>
				<%= form_for([@provider, @booking]) do |f| %>
					<div class="field">
						<%= f.label :time %>
						<%= f.time_field :time, class: 'input-background',  value: "%H:%M", min: '08:00:00', max: '16:00:00' %>
					</div>
					<div class="field">
						<%= f.label :date %>
						<%= f.date_field :date, class: 'input-background', min: Date.current, max: 1.month.from_now %>
					</div>
						<div class="field">
						<%= f.label :comments %>
						<%= f.text_area :comments, class: 'input-background' %>
					</div>				
					<%= f.submit "Confirm booking", class: 'btn btn-secondary mt-3' %>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/chatrooms/index.html.erb
<div class="container">
    <div class="row pt-5">
        <div class="col-12 col-md-10 col-lg-6 m-auto pt-5">
            <h3>Your messages</h3>
            <ul class="list-group">
                <% if !@provider_chats.empty? %>
                    <li class="list-group-item border-0 d-flex justify-content-between align-items-center">
                        <p>From</p>
                        <p>Last message</p>
                        <%# <span class="badge bg-primary rounded-pill">14</span> %>
                    </li>
                <% end %>
                <% @provider_chats.each do |chat| %>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <%= link_to chat.provider.name, chatroom_path(chat.id) %> <%= chat.messages.last.content %>
                        <%# <span class="badge bg-primary rounded-pill">14</span> %>
                    </li>
                <% end %>
            </ul>
            <h3>Your provider account messages</h3>
            <ul class="list-group">
                <% if !@user_chats.empty? ||  %>
                    <li class="list-group-item border-0 d-flex justify-content-between align-items-center">
                        <p class="mb-0">From</p>
                        <p class="mb-0">Last message</p>
                        <%# <span class="badge bg-primary rounded-pill">14</span> %>
                    </li>
                <% end %>
                <% @user_chats.each do |chat| %>
                    <li class="list-group-item d-flex justify-content-between border-top align-items-center">
                        <%= link_to chat.user.username, chatroom_path(chat.id) %> <%= chat.messages.last.content %>
                        <%# <span class="badge bg-primary rounded-pill">14</span> %>
                    </li>
                <% end %>
            </ul>
        </div>
    </div>
</div>

app/views/chatrooms/show.html.erb
<div class="container-fluid chat-container">
  <div class="row">
    <div class="col-12 col-md-8 col-lg-6 col-xl-4 m-auto pt-5 inner-container">
      <div class="chat-info-container">
        <div id="messages" data-chatroom-id="<%= @chatroom.id %>" class="messages">
          <% @chatroom.messages.each do |message| %>
            <div class="message-container" id="message-<%= message.id %>">
              <div class="chat-bubble mb-3 <%=  message.user == current_user ? "message-author" : "message-recipient" %>">
                <i class="author">
                  <span><%= message.user.username %></span>
                  <small><%= message.created_at.strftime("%a %b %e at %l:%M%p") %></small>
                </i>
                <p><%= message.content %></p>
              </div>
            </div>
          <% end %>
        </div>
      </div>  
      <div class="chat-form-wrapper" >
        <div class="chat-form ">
          <%= form_for [ @chatroom, @message ], remote: true do |f| %>
            <%= f.text_field :content, as: :text, label: false, placeholder: "Chat with #{@chatroom.provider.name}", autofocus: true %>
            <button type="submit" class="chat-button">
              <i class="fas fa-chevron-circle-right fa-2x"></i>
            </button>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/messages/_message.html.erb
<div class="message-container" id="message-<%= message.id %>">
  <div class="chat-bubble mb-3 <%=  message.user == current_user ? "message-author" : "message-recipient" %>">
    <i class="author">
      <span><%= message.user.username %></span>
      <small><%= message.created_at.strftime("%a %b %e at %l:%M%p") %></small>
    </i>
    <p><%= message.content %></p>
  </div>
</div>

app/views/users/bookings.html.erb
<div class="container-fluid booking-index-container">
    <div class="row pt-5">
        <div class="col-12 col-md-10 col-lg-6 m-auto pt-5">
            <% if user_signed_in? %>
                <% if !current_user.bookings.empty? %>
                    <% current_user.bookings.each do |booking| %>
                    <div class="card mb-3 m-auto" style="max-width: 540px;">
                        <div class="row g-0">
                        <div class="col-md-4">
                            <%= cl_image_tag booking.provider.photos[0].key, crop: :fill, gravity: :face, class: 'bookings-provider-image h-100' %>
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                            <h5 class="card-title"><%= booking.provider.name %></h5>
                            <h6 class="card-text"><%= booking.provider.service_type %></h6>
                            <p class="card-text mb-0"><i class="fas fa-money-bill-wave"></i> €<%= booking.provider.rate %></p>
                            <p class="card-text mb-0"><i class="fas fa-map-pin"></i> <%= booking.provider.location %></p>
                            <p class="card-text mb-0"><i class="fas fa-clock"></i> <%= booking.date.strftime("%a %b %d, %Y") %> - <%= booking.time.strftime("%H:%M") %></p>
                            <p class="card-text mb-0"><i class="fas fa-language"></i>
                                <% languages = booking.provider.languages.split(', ') %>
                                <% languages.each do |lan| %>
                                <span><%= lan %></span>
                                <% end %>
                            </p>
                            <% if booking.pending %>
                                <div class="alert alert-warning mb-0" role="alert">
                                Pending for approval
                                </div>
                            <% else %>
                                <div class="alert alert-success mb-0" role="alert">
                                Booking confirmed
                                </div>
                            <% end %>
                            <p class="card-text">Comments: <%= booking.comments %></p>
                            </div>
                        </div>
                        </div>
                    </div>
                    <% end %>
                <% else %>
                    <h6 class="">You have not book services yet.</h6>
                <% end %>
            <% end %>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<div class="container-fluid profile-page">
  <div class="row">
    <div class="col-12 col-md-10 col-lg-6 mx-auto mt-4">
      <div class="profile-container">
          <%= link_to edit_user_registration_path(@user), class: 'btn btn-outline-secondary edit-profile-btn' do %>
            <i class="far fa-edit"></i>
          <% end %>
          <% if !@user.photo.attachment.nil? %>
            <%= cl_image_tag @user.photo.key, height: 300, width: 400, crop: :fill, gravity: :face %>
          <% else %>
            <img src="https://res.cloudinary.com/dliczkabg/image/upload/v1610983854/profile-silhouette_oychwo.jpg" alt="">
          <% end %> 
        
        <div class="profile-info">
          <h1><%= @user.username.capitalize %></h1>
          <div>
            <h6><i class="far fa-envelope"></i> <%= @user.email %></h6>
          </div>
          <div>
            <h6><i class="fas fa-map-pin"></i> <%= @user.location %></h6>
          </div>
          <div>
            <h6><i class="fas fa-language"></i> <%= @user.preferred_language %></h6>
          </div>
          <div class="mt-3">
            <h5 class="mb-0">About me:</h5>
            <h6><%= @user.description %></h6>
          </div>
        </div>
      </div>
      <% if !@user.provider %>
        <div class="profile-action">
          <h3>Speak many languages?</h3>
          <%= link_to  "Become a provider", new_provider_path, class: "btn btn-secondary" %>
        </div>
      <% else %>
        <div class="profile-action">
          <%= link_to  "View my services", provider_path(Provider.find_by(user_id: @user.id)), class: "btn btn-secondary" %>
        </div>
      <% end %>
      
    </div>
  </div>
</div>