config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/categories', to: 'pages#categories'
  get '/profile/:id', as: 'profile', to: 'users#show'
  get '/:id/booking', as: 'users_bookings', to: 'users#bookings'
  get '/providers/all', as: 'all_providers', to: 'providers#all' 
  resources :providers do
    get 'provider/:id/bookings/:id/confirmation',as: 'booking_confirmation', to: 'bookings#confirmation'
    resources :bookings do
      resources :payments, only: :new
    end
    resources :reviews, only: :create
  end
  resources :chatrooms, only: [:new, :create, :show, :index] do 
    resources :messages, only: :create
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :provider
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  belongs_to :user
  belongs_to :provider
  has_many :messages, dependent: :destroy
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :provider
  belongs_to :chatroom
end

app/models/provider.rb
class Provider < ApplicationRecord

  include PgSearch::Model

  pg_search_scope :global_search,
    against: [ :service_type, :name ],
  #   associated_against: {
  #     users: [ :username, :service_type ]
  # },
    using: {
      tsearch: { prefix: true }
  }

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  serialize :languages
  belongs_to :user
  has_many_attached :photos
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :chatrooms, dependent: :destroy
  validates :name, :service_type, :rate, :location, :description, :languages, presence: true
  validates :name, uniqueness: true

  def rating
    return 0 if self.reviews.empty?

    total = self.reviews.sum(:rating)
    total / self.reviews.count
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :provider
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :photo
  has_many :bookings
  has_many :reviews
  has_many :chatrooms
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = policy_scope(Booking).where(user_id: current_user.id)
    provider = Provider.find_by(user_id: current_user.id)
    @requests = Booking.count > 0 ? Booking.where(provider_id: provider.id) : []
    
    authorize @bookings
  end

  def new
    @booking = Booking.new
    @provider = Provider.find(params[:provider_id])
  end
  def show
    @booking = current_user.bookings.find(params[:id])
  end

  def create
    @booking = Booking.new(booking_params)
    @provider = Provider.find(params[:provider_id])
    @booking.provider = @provider
    @booking.user = current_user
    @booking.save!
    session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      line_items: [{
        name: @booking.provider.name,
        amount: @booking.provider.rate.to_i * 100,
        currency: 'eur',
        quantity: 1
      }],
      success_url:  provider_booking_confirmation_url(@provider, @booking),
      cancel_url: provider_url(@booking.provider)
    )
    
    @booking.update(checkout_session_id: session.id)
    redirect_to new_provider_booking_payment_path(@provider, @booking)
  end

  def destroy
    @booking = Booking.find(params[:id])
    @user = User.find(@booking.user_id)
    @booking.destroy
    redirect_to profile_path(@user)
  end

  def confirmation
    @booking = Booking.find(params[:id])
    @booking.pending = false
    @booking.save!
    redirect_to provider_bookings_path(@booking.provider)
  end

  private

  def booking_params
    params.require(:booking).permit(:date, :time, :user, :provider_id, :comments)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    skip_before_action :authenticate_user!, only: [:home, :categories]
    def home
    end

    def categories
        @categories = []
        
        Provider.all.each do |provider|
            @categories << provider.service_type
        end
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    def create
        @review = Review.new(review_params)
        @review.user = current_user
        @provider = Provider.find(params[:provider_id])
        @review.provider_id = @provider.id
        if @review.save!
            redirect_to provider_path(@provider)
        else

        end

    end

    private

    def review_params
        params.require(:review).permit(:rating, :content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id])
        
        @provider = Provider.find_by(user_id: @user.id)
        if @provider.nil? 
            @request = []
        else
            @requests = Booking.count > 0 ? Booking.where(provider_id: @provider.id) : []
        end
        authorize @user
    end

    def bookings
        @bookings = Booking.where(user_id: current_user.id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Babylon | Home</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>
    <script src='https://api.mapbox.com/mapbox-gl-js/v2.0.0/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v2.0.0/mapbox-gl.css' rel='stylesheet' />
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="https://kit.fontawesome.com/8631d0c616.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pages/categories.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-md-10 col-lg-6 m-auto pt-3">
      <div class="pt-5">
      <h2>Search by category</h2>
      <% @categories.each do |category| %>
        <%= link_to providers_path(category), class: 'text-decoration-none' do %>
        <% string = category.split(' ').first %>
          <div class="col-12 lg-6 category-card " style="background-image: url(https://source.unsplash.com/featured/?<%= string %>)">
            <div class="card-content ">
              <h4><%= category %></h4>
            </div>
          </div>
        <% end %>
      <% end %>
      <%= link_to  all_providers_path, class: 'text-decoration-none' do %>
          <div class="col-12 lg-6 category-card" style="background-image: url(https://source.unsplash.com/featured/?services)">
            <div class="card-content">
              <h4>All Categories</h4>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container-fluid" data-controller="location">
  <div class="row home-container">
    <div class="col-12 md-6">
      <div class="brand-banner">
        <h1>Babylon</h1>
        <h2 class="display-1">Find services in your own language</h2>
        <%# <a href="/categories" class="btn btn-secondary ">Find professionals in your area</a> %>
        <div>
          <form novalidate="novalidate" class="simple_form search hide-location" data-location-target="form" action="/providers/all" accept-charset="UTF-8" method="get">
            <input name="utf8" type="hidden" value="&#x2713;" />
            <div class="search-form-control form-group" data-controller="algolia">
              <input class="form-control string required" type="text" name="query" id="search_query" placeholder="Look up services"/>
              <input class="form-control string mt-3" placeholder="Type your location" type="hidden" name="location" id="bar_address" data-location-target="location" data-algolia-target="location">
              <input type="hidden" name="latitude" data-location-target="latitudeInput">
              <input type="hidden" name="longitude" data-location-target="longitudeInput">
            </div>
            <button type="submit" class="btn btn-secondary col text-center">Search</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="/"><i class="fas fa-user-tie"></i> Babylon</a>
    <% if user_signed_in? %>
      <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <% if !current_user.photo.attachment.nil? %>
          <%= cl_image_tag current_user.photo.key, height: 300, width: 400, crop: :fill, gravity: :face, width: 40, height: 40, class: 'rounded-circle' %>
        <% else %>
          <img src="https://res.cloudinary.com/dliczkabg/image/upload/v1610983854/profile-silhouette_oychwo.jpg" alt="" class="navbar-avatar">
        <% end %>
      </button>
    <% else %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    <% end %>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item text-center">
          <a class="nav-link" href="/categories">Book services</a>
        </li>
        <%if  user_signed_in? %>
          <li class="nav-item text-center">
            <a class="nav-link" href="/profile/<%= current_user.id %>">Profile</a>
          </li>
          <li class="nav-item text-center">
            <a class="nav-link" href="/chatrooms">Messages</a>
          </li>
          <% if current_user.provider == true %>
            <li class="nav-item text-center">
              <% provider = Provider.find_by(user_id: current_user.id) %>
              <%= link_to 'Bookings', provider_bookings_path(provider), class: 'nav-link' %>
            </li>
          <% else %>
            <li class="nav-item text-center">
              
              <% provider = Provider.find_by(user_id: current_user.id) %>
            <%= link_to 'Bookings', users_bookings_path(current_user.id), class: 'nav-link' %>
          </li>
          <% end %>
        <% end %>
        <% if user_signed_in?%>
          <li class="nav-item text-center">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item text-center">
            <%= link_to "Register", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item text-center">
            <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>